<?php

namespace endoviTheme\Blocks\Equipment;

defined( 'ABSPATH' ) || exit;

add_action( 'init', __NAMESPACE__ . '\\register_block' );
add_action( 'init', __NAMESPACE__ . '\\register_fields' );

/**
 * Registers all block assets so that they can be enqueued through Gutenberg
 * in the corresponding context.
 */
function register_block() {
	register_block_type( __DIR__ );
}

/**
 * Register block fields
 * @return void
 */
function register_fields() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group(
		array(
			'key'                   => 'group_6a6a3bad5a409',
			'title'                 => esc_attr__( 'Блок Комплектация', 'endovi' ),
			'fields'                => array(
				array(
					'key'               => 'field_6a6a3baee7d88',
					'label'             => esc_attr__( 'Скрыть', 'endovi' ),
					'name'              => 'equipment_hide',
					'aria-label'        => '',
					'type'              => 'true_false',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'message'           => '',
					'default_value'     => 0,
					'allow_in_bindings' => 0,
					'ui_on_text'        => '',
					'ui_off_text'       => '',
					'ui'                => 1,
				),
				array(
					'key'               => 'field_6a6a3bf49920a',
					'label'             => esc_attr__( 'Заголовок', 'endovi' ),
					'name'              => 'equipment_title',
					'aria-label'        => '',
					'type'              => 'textarea',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'maxlength'         => '',
					'allow_in_bindings' => 0,
					'rows'              => 2,
					'placeholder'       => '',
					'new_lines'         => 'br',
				),
				array(
					'key'               => 'field_6a6a3c15e59f3',
					'label'             => esc_attr__( 'Изображение', 'endovi' ),
					'name'              => 'equipment_image',
					'aria-label'        => '',
					'type'              => 'image',
					'instructions'      => esc_attr__( 'Десктоп', 'endovi' ),
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '50',
						'class' => '',
						'id'    => '',
					),
					'return_format'     => 'id',
					'library'           => 'all',
					'min_width'         => '',
					'min_height'        => '',
					'min_size'          => '',
					'max_width'         => '',
					'max_height'        => '',
					'max_size'          => '',
					'mime_types'        => '',
					'allow_in_bindings' => 0,
					'preview_size'      => 'medium',
				),
				array(
					'key'               => 'field_6a6a3c4d1d820',
					'label'             => esc_attr__( 'Изображение', 'endovi' ),
					'name'              => 'equipment_image_mobile',
					'aria-label'        => '',
					'type'              => 'image',
					'instructions'      => esc_attr__( 'Мобайл', 'endovi' ),
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '50',
						'class' => '',
						'id'    => '',
					),
					'return_format'     => 'id',
					'library'           => 'all',
					'min_width'         => '',
					'min_height'        => '',
					'min_size'          => '',
					'max_width'         => '',
					'max_height'        => '',
					'max_size'          => '',
					'mime_types'        => '',
					'allow_in_bindings' => 0,
					'preview_size'      => 'medium',
				),
				array(
					'key'               => 'field_6a6a3ceecc867',
					'label'             => esc_attr__( 'Комплектация', 'endovi' ),
					'name'              => 'equipment_items',
					'aria-label'        => '',
					'type'              => 'repeater',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'row',
					'pagination'        => 0,
					'min'               => 0,
					'max'               => 0,
					'collapsed'         => '',
					'button_label'      => esc_attr__( 'Добавить', 'endovi' ),
					'rows_per_page'     => 20,
					'sub_fields'        => array(
						array(
							'key'               => 'field_6a6a3d0fcc868',
							'label'             => esc_attr__( 'Позиция', 'endovi' ),
							'name'              => 'position',
							'aria-label'        => '',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'maxlength'         => '',
							'allow_in_bindings' => 0,
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'parent_repeater'   => 'field_6a6a3ceecc867',
						),
						array(
							'key'               => 'field_6a6a3d41cc869',
							'label'             => esc_attr__( 'Количество', 'endovi' ),
							'name'              => 'count',
							'aria-label'        => '',
							'type'              => 'number',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_6a6a3de6ec96d',
										'operator' => '==empty',
									),
								),
							),
							'wrapper'           => array(
								'width' => '5',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'min'               => 1,
							'max'               => '',
							'allow_in_bindings' => 0,
							'placeholder'       => '',
							'step'              => 1,
							'prepend'           => '',
							'append'            => '',
							'parent_repeater'   => 'field_6a6a3ceecc867',
						),
						array(
							'key'               => 'field_6a6a3d8ecc86a',
							'label'             => esc_attr__( 'Единица измерения', 'endovi' ),
							'name'              => 'unit',
							'aria-label'        => '',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_6a6a3de6ec96d',
										'operator' => '==empty',
									),
								),
							),
							'wrapper'           => array(
								'width' => '5',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => esc_attr__( 'шт', 'endovi' ),
							'maxlength'         => 10,
							'allow_in_bindings' => 0,
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'parent_repeater'   => 'field_6a6a3ceecc867',
						),
						array(
							'key'               => 'field_6a6a3de6ec96d',
							'label'             => esc_attr__( 'Подпозиции', 'endovi' ),
							'name'              => 'items',
							'aria-label'        => '',
							'type'              => 'repeater',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_6a6a3d41cc869',
										'operator' => '==empty',
									),
								),
							),
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'table',
							'pagination'        => 0,
							'min'               => 0,
							'max'               => 0,
							'collapsed'         => '',
							'button_label'      => esc_attr__( 'Добавить', 'endovi' ),
							'rows_per_page'     => 20,
							'sub_fields'        => array(
								array(
									'key'               => 'field_6a6a3e29ec96e',
									'label'             => esc_attr__( 'Подпозиция', 'endovi' ),
									'name'              => 'position',
									'aria-label'        => '',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'maxlength'         => '',
									'allow_in_bindings' => 0,
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'parent_repeater'   => 'field_6a6a3de6ec96d',
								),
								array(
									'key'               => 'field_6a6a3e70ec96f',
									'label'             => esc_attr__( 'Количество', 'endovi' ),
									'name'              => 'count',
									'aria-label'        => '',
									'type'              => 'number',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '5',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'min'               => 1,
									'max'               => '',
									'allow_in_bindings' => 0,
									'placeholder'       => '',
									'step'              => 1,
									'prepend'           => '',
									'append'            => '',
									'parent_repeater'   => 'field_6a6a3de6ec96d',
								),
								array(
									'key'               => 'field_6a6a3eccec970',
									'label'             => esc_attr__( 'Единица измерения', 'endovi' ),
									'name'              => 'unit',
									'aria-label'        => '',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '5',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => esc_attr__( 'шт', 'endovi' ),
									'maxlength'         => 10,
									'allow_in_bindings' => 0,
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'parent_repeater'   => 'field_6a6a3de6ec96d',
								),
							),
							'parent_repeater'   => 'field_6a6a3ceecc867',
						),
					),
				),
				array(
					'key'               => 'field_69cfd3f664bn5',
					'label'             => esc_attr__( 'Заметка', 'endovi' ),
					'name'              => 'equipment_note',
					'aria-label'        => '',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'maxlength'         => '',
					'allow_in_bindings' => 0,
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'block',
						'operator' => '==',
						'value'    => 'endovi/equipment',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
			'show_in_rest'          => 0,
			'display_title'         => '',
		)
	);
}
