<?php

namespace endoviTheme\Blocks\Alternating;

defined( 'ABSPATH' ) || exit;

add_action( 'init', __NAMESPACE__ . '\\register_block' );
add_action( 'init', __NAMESPACE__ . '\\register_fields' );

/**
 * Registers all block assets so that they can be enqueued through Gutenberg
 * in the corresponding context.
 */
function register_block() {
	register_block_type( __DIR__ );
}

/**
 * Register block fields
 * @return void
 */
function register_fields() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group(
		array(
			'key'                   => 'group_6a85eef2606cd',
			'title'                 => esc_attr__( 'Блок Чередование карточек', 'endovi' ),
			'fields'                => array(
				array(
					'key'               => 'field_6a85eef362b60',
					'label'             => esc_attr__( 'Скрыть', 'endovi' ),
					'name'              => 'alternating_hide',
					'aria-label'        => '',
					'type'              => 'true_false',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'message'           => '',
					'default_value'     => 0,
					'allow_in_bindings' => 0,
					'ui_on_text'        => '',
					'ui_off_text'       => '',
					'ui'                => 1,
				),
				array(
					'key'               => 'field_6a85ef3e62b61',
					'label'             => esc_attr__( 'Заголовок', 'endovi' ),
					'name'              => 'alternating_title',
					'aria-label'        => '',
					'type'              => 'textarea',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'maxlength'         => '',
					'allow_in_bindings' => 0,
					'rows'              => 2,
					'placeholder'       => '',
					'new_lines'         => 'br',
				),
				array(
					'key'               => 'field_6a85ef6062b62',
					'label'             => esc_attr__( 'Карточки', 'endovi' ),
					'name'              => 'alternating_items',
					'aria-label'        => '',
					'type'              => 'repeater',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'row',
					'pagination'        => 0,
					'min'               => 0,
					'max'               => 0,
					'collapsed'         => '',
					'button_label'      => esc_attr__( 'Добавить', 'endovi' ),
					'rows_per_page'     => 20,
					'sub_fields'        => array(
						array(
							'key'               => 'field_6a85ef8362b63',
							'label'             => esc_attr__( 'Заголовок', 'endovi' ),
							'name'              => 'title',
							'aria-label'        => '',
							'type'              => 'textarea',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'maxlength'         => '',
							'allow_in_bindings' => 0,
							'rows'              => 4,
							'placeholder'       => '',
							'new_lines'         => 'br',
							'parent_repeater'   => 'field_6a85ef6062b62',
						),
						array(
							'key'               => 'field_6a85efb462b64',
							'label'             => esc_attr__( 'Подзаголовок', 'endovi' ),
							'name'              => 'sub_title',
							'aria-label'        => '',
							'type'              => 'textarea',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'maxlength'         => '',
							'allow_in_bindings' => 0,
							'rows'              => 4,
							'placeholder'       => '',
							'new_lines'         => 'br',
							'parent_repeater'   => 'field_6a85ef6062b62',
						),
						array(
							'key'               => 'field_6a85efeb62b65',
							'label'             => esc_attr__( 'Описание', 'endovi' ),
							'name'              => 'description',
							'aria-label'        => '',
							'type'              => 'textarea',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'maxlength'         => '',
							'allow_in_bindings' => 0,
							'rows'              => 4,
							'placeholder'       => '',
							'new_lines'         => 'br',
							'parent_repeater'   => 'field_6a85ef6062b62',
						),
						array(
							'key'               => 'field_6a85f02662b66',
							'label'             => esc_attr__( 'Нижний блок', 'endovi' ),
							'name'              => 'footer',
							'aria-label'        => '',
							'type'              => 'wysiwyg',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'allow_in_bindings' => 0,
							'tabs'              => 'all',
							'toolbar'           => 'heading_list',
							'media_upload'      => 0,
							'delay'             => 0,
							'parent_repeater'   => 'field_6a85ef6062b62',
						),
						array(
							'key'               => 'field_6a85f05c62b67',
							'label'             => esc_attr__( 'Иконка', 'endovi' ),
							'name'              => 'icon',
							'aria-label'        => '',
							'type'              => 'image',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'id',
							'library'           => 'all',
							'min_width'         => '',
							'min_height'        => '',
							'min_size'          => '',
							'max_width'         => '',
							'max_height'        => '',
							'max_size'          => '',
							'mime_types'        => '',
							'allow_in_bindings' => 0,
							'preview_size'      => 'medium',
							'parent_repeater'   => 'field_6a85ef6062b62',
						),
						array(
							'key'               => 'field_6a8716d06cff7',
							'label'             => esc_attr__( 'Изображения', 'endovi' ),
							'name'              => 'images',
							'aria-label'        => '',
							'type'              => 'repeater',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'table',
							'pagination'        => 0,
							'min'               => 0,
							'max'               => 3,
							'collapsed'         => '',
							'button_label'      => esc_attr__( 'Добавить', 'endovi' ),
							'rows_per_page'     => 20,
							'sub_fields'        => array(
								array(
									'key'               => 'field_6a87174d6cff8',
									'label'             => esc_attr__( 'Изображение', 'endovi' ),
									'name'              => 'image',
									'aria-label'        => '',
									'type'              => 'image',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'return_format'     => 'id',
									'library'           => 'all',
									'min_width'         => '',
									'min_height'        => '',
									'min_size'          => '',
									'max_width'         => '',
									'max_height'        => '',
									'max_size'          => '',
									'mime_types'        => '',
									'allow_in_bindings' => 0,
									'preview_size'      => 'medium',
									'parent_repeater'   => 'field_6a8716d06cff7',
								),
								array(
									'key'               => 'field_6a8717726cff9',
									'label'             => esc_attr__( 'Заголовок', 'endovi' ),
									'name'              => 'title',
									'aria-label'        => '',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'maxlength'         => '',
									'allow_in_bindings' => 0,
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'parent_repeater'   => 'field_6a8716d06cff7',
								),
							),
							'parent_repeater'   => 'field_6a85ef6062b62',
						),
					),
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'block',
						'operator' => '==',
						'value'    => 'endovi/alternating',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
			'show_in_rest'          => 0,
			'display_title'         => '',
		)
	);
}
