<?php

namespace endoviTheme\Blocks\Catalog;

use endoviTheme\Constants\Constants;

defined( 'ABSPATH' ) || exit;

add_action( 'init', __NAMESPACE__ . '\\register_block' );
add_action( 'init', __NAMESPACE__ . '\\register_fields' );

/**
 * Registers all block assets so that they can be enqueued through Gutenberg
 * in the corresponding context.
 */
function register_block() {
	register_block_type( __DIR__ );
}

/**
 * Register block fields
 * @return void
 */
function register_fields() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group(
		array(
			'key'                   => 'group_6a81dd5404579',
			'title'                 => esc_attr__( 'Блок Каталог', 'endovi' ),
			'fields'                => array(
				array(
					'key'               => 'field_6a81f953b89d6',
					'label'             => esc_attr__( 'Скрыть', 'endovi' ),
					'name'              => 'catalog_hide',
					'aria-label'        => '',
					'type'              => 'true_false',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'message'           => '',
					'default_value'     => 0,
					'allow_in_bindings' => 0,
					'ui_on_text'        => '',
					'ui_off_text'       => '',
					'ui'                => 1,
				),
				array(
					'key'               => 'field_6a81dd5994ad4',
					'label'             => esc_attr__( 'Показывать крошки', 'endovi' ),
					'name'              => 'catalog_breadcrumbs',
					'aria-label'        => '',
					'type'              => 'true_false',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'message'           => '',
					'default_value'     => 0,
					'allow_in_bindings' => 0,
					'ui_on_text'        => '',
					'ui_off_text'       => '',
					'ui'                => 1,
				),
				array(
					'key'               => 'field_6a81f9a0b89d7',
					'label'             => '',
					'name'              => 'catalog_is_h1',
					'aria-label'        => '',
					'type'              => 'true_false',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'message'           => '',
					'default_value'     => 0,
					'allow_in_bindings' => 0,
					'ui_on_text'        => 'h1',
					'ui_off_text'       => 'h2',
					'ui'                => 1,
				),
				array(
					'key'               => 'field_6a81f9cdb89d8',
					'label'             => esc_attr__( 'Заголовок', 'endovi' ),
					'name'              => 'catalog_title',
					'aria-label'        => '',
					'type'              => 'textarea',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'maxlength'         => '',
					'allow_in_bindings' => 0,
					'rows'              => 2,
					'placeholder'       => '',
					'new_lines'         => 'br',
				),
				array(
					'key'               => 'field_6a81fa09c2c8d',
					'label'             => esc_attr__( 'Табы', 'endovi' ),
					'name'              => 'catalog_tabs',
					'aria-label'        => '',
					'type'              => 'repeater',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'pagination'        => 0,
					'min'               => 0,
					'max'               => 2,
					'collapsed'         => '',
					'button_label'      => esc_attr__( 'Добавить', 'endovi' ),
					'rows_per_page'     => 20,
					'sub_fields'        => array(
						array(
							'key'               => 'field_6a81fa31c2c8e',
							'label'             => esc_attr__( 'Заголовок таба', 'endovi' ),
							'name'              => 'title',
							'aria-label'        => '',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'maxlength'         => '',
							'allow_in_bindings' => 0,
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'parent_repeater'   => 'field_6a81fa09c2c8d',
						),
						array(
							'key'               => 'field_6a81fa65c2c8f',
							'label'             => '',
							'name'              => 'is_type',
							'aria-label'        => '',
							'type'              => 'true_false',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'message'           => '',
							'default_value'     => 0,
							'allow_in_bindings' => 0,
							'ui_on_text'        => esc_attr__( 'Типы', 'endovi' ),
							'ui_off_text'       => esc_attr__( 'Серии', 'endovi' ),
							'ui'                => 1,
							'parent_repeater'   => 'field_6a81fa09c2c8d',
						),
						array(
							'key'               => 'field_6a81faa0c2c90',
							'label'             => esc_attr__( 'Категории', 'endovi' ),
							'name'              => 'categories',
							'aria-label'        => '',
							'type'              => 'repeater',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'row',
							'pagination'        => 0,
							'min'               => 0,
							'max'               => 0,
							'collapsed'         => '',
							'button_label'      => esc_attr__( 'Добавить', 'endovi' ),
							'rows_per_page'     => 20,
							'sub_fields'        => array(
								array(
									'key'               => 'field_6a81facfc2c91',
									'label'             => esc_attr__( 'Цвет', 'endovi' ),
									'name'              => 'is_gradient',
									'aria-label'        => '',
									'type'              => 'true_false',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => array(
										array(
											array(
												'field'    => 'field_6a81fa65c2c8f',
												'operator' => '!=',
												'value'    => '1',
											),
										),
									),
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'message'           => '',
									'default_value'     => 0,
									'allow_in_bindings' => 0,
									'ui_on_text'        => esc_attr__( 'Градиент', 'endovi' ),
									'ui_off_text'       => esc_attr__( 'Сплошной', 'endovi' ),
									'ui'                => 1,
									'parent_repeater'   => 'field_6a81faa0c2c90',
								),
								array(
									'key'               => 'field_6a81fb28c2c92',
									'label'             => esc_attr__( 'Заголовок категории', 'endovi' ),
									'name'              => 'title',
									'aria-label'        => '',
									'type'              => 'textarea',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'maxlength'         => '',
									'allow_in_bindings' => 0,
									'rows'              => 2,
									'placeholder'       => '',
									'new_lines'         => 'br',
									'parent_repeater'   => 'field_6a81faa0c2c90',
								),
								array(
									'key'               => 'field_6a81fb6cc2c93',
									'label'             => esc_attr__( 'Изображение', 'endovi' ),
									'name'              => 'image',
									'aria-label'        => '',
									'type'              => 'image',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'return_format'     => 'id',
									'library'           => 'all',
									'min_width'         => '',
									'min_height'        => '',
									'min_size'          => '',
									'max_width'         => '',
									'max_height'        => '',
									'max_size'          => '',
									'mime_types'        => '',
									'allow_in_bindings' => 0,
									'preview_size'      => 'medium',
									'parent_repeater'   => 'field_6a81faa0c2c90',
								),
								array(
									'key'               => 'field_6a81fb8dc2c94',
									'label'             => esc_attr__( 'Ссылки', 'endovi' ),
									'name'              => 'items',
									'aria-label'        => '',
									'type'              => 'repeater',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'layout'            => 'table',
									'pagination'        => 0,
									'min'               => 0,
									'max'               => 0,
									'collapsed'         => '',
									'button_label'      => esc_attr__( 'Добавить', 'endovi' ),
									'rows_per_page'     => 20,
									'sub_fields'        => array(
										array(
											'key'          => 'field_6a81fbb0c2c95',
											'label'        => esc_attr__( 'Заголовок товара', 'endovi' ),
											'name'         => 'title',
											'aria-label'   => '',
											'type'         => 'text',
											'instructions' => '',
											'required'     => 0,
											'conditional_logic' => 0,
											'wrapper'      => array(
												'width' => '',
												'class' => '',
												'id'    => '',
											),
											'default_value' => '',
											'maxlength'    => '',
											'allow_in_bindings' => 0,
											'placeholder'  => '',
											'prepend'      => '',
											'append'       => '',
											'parent_repeater' => 'field_6a81fb8dc2c94',
										),
										array(
											'key'          => 'field_6a81fbe4c2c96',
											'label'        => esc_attr__( 'Ссылка', 'endovi' ),
											'name'         => 'link',
											'aria-label'   => '',
											'type'         => 'page_link',
											'instructions' => '',
											'required'     => 0,
											'conditional_logic' => 0,
											'wrapper'      => array(
												'width' => '',
												'class' => '',
												'id'    => '',
											),
											'post_type'    => array(
												0 => Constants::PT_SLUG_CATALOG,
											),
											'post_status'  => '',
											'taxonomy'     => '',
											'allow_archives' => 0,
											'multiple'     => 0,
											'allow_null'   => 0,
											'allow_in_bindings' => 0,
											'parent_repeater' => 'field_6a81fb8dc2c94',
										),
									),
									'parent_repeater'   => 'field_6a81faa0c2c90',
								),
							),
							'parent_repeater'   => 'field_6a81fa09c2c8d',
						),
					),
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'block',
						'operator' => '==',
						'value'    => 'endovi/catalog',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
			'show_in_rest'          => 0,
			'display_title'         => '',
		)
	);
}
