<?php
if ( function_exists( 'acf_add_local_field_group' ) ) {
	acf_add_local_field_group(
		array(
			'key'                   => 'group_66d5c4ea5e440',
			'title'                 => esc_attr__( 'Options', 'endovi' ),
			'fields'                => array(
				array(
					'key'               => 'field_69cfd37e7b3e5',
					'label'             => esc_attr__( 'Общие', 'endovi' ),
					'name'              => '',
					'aria-label'        => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'left',
					'endpoint'          => 0,
					'selected'          => 0,
				),
				array(
					'key'               => 'field_6a5b9dd7d2590',
					'label'             => esc_attr__( 'Страница каталога', 'endovi' ),
					'name'              => 'catalog_page',
					'aria-label'        => '',
					'type'              => 'page_link',
					'instructions'      => '',
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'post_type'         => array(
						0 => 'page',
					),
					'post_status'       => '',
					'taxonomy'          => '',
					'allow_archives'    => 0,
					'multiple'          => 0,
					'allow_null'        => 0,
					'allow_in_bindings' => 0,
				),
				array(
					'key'               => 'field_69cfd37e7b27f',
					'label'             => esc_attr__( 'Подвал', 'endovi' ),
					'name'              => '',
					'aria-label'        => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'left',
					'endpoint'          => 0,
					'selected'          => 0,
				),
				array(
					'key'               => 'field_69cfd3f664jk6',
					'label'             => esc_attr__( 'Заголовок формы', 'endovi' ),
					'name'              => 'footer_form_title',
					'aria-label'        => '',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'maxlength'         => '',
					'allow_in_bindings' => 0,
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
				),
				array(
					'key'                  => 'field_69cfd3aa7b280',
					'label'                => esc_attr__( 'Форма', 'endovi' ),
					'name'                 => 'footer_form',
					'aria-label'           => '',
					'type'                 => 'post_object',
					'instructions'         => '',
					'required'             => 0,
					'conditional_logic'    => 0,
					'wrapper'              => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'post_type'            => array(
						0 => 'wpcf7_contact_form',
					),
					'post_status'          => array(
						0 => 'publish',
					),
					'taxonomy'             => '',
					'return_format'        => 'id',
					'multiple'             => 0,
					'allow_null'           => 0,
					'allow_in_bindings'    => 0,
					'bidirectional'        => 0,
					'ui'                   => 1,
					'bidirectional_target' => array(),
				),
				array(
					'key'               => 'field_69cfd3f66412c',
					'label'             => esc_attr__( 'Копирайт', 'endovi' ),
					'name'              => 'footer_copyright',
					'aria-label'        => '',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'maxlength'         => '',
					'allow_in_bindings' => 0,
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
				),
				array(
					'key'               => 'field_69cfd4186412d',
					'label'             => esc_attr__( 'Политика конфиденциальности', 'endovi' ),
					'name'              => 'footer_policy',
					'aria-label'        => '',
					'type'              => 'page_link',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'post_type'         => array(
						0 => 'page',
					),
					'post_status'       => array(
						0 => 'publish',
					),
					'taxonomy'          => '',
					'allow_archives'    => 0,
					'multiple'          => 0,
					'allow_null'        => 0,
					'allow_in_bindings' => 0,
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'options_page',
						'operator' => '==',
						'value'    => 'endovi-options',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
			'show_in_rest'          => 0,
		)
	);
}
